//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSistema.ModeloDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFacVenta
    {
        public int Id { get; set; }
        public decimal PrecioVenta { get; set; }
        public int Cantidad { get; set; }
        public decimal Subtotal { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public int ProductoId { get; set; }
        public int FacturaVentaId { get; set; }
    
        public virtual FacturaVenta FacturaVenta { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
