//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSistema.ModeloDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaVenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FacturaVenta()
        {
            this.DetalleFacVenta = new HashSet<DetalleFacVenta>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string NombreClente { get; set; }
        public decimal MontoPago { get; set; }
        public decimal MontoCambio { get; set; }
        public decimal MontoTotal { get; set; }
        public Nullable<System.DateTime> FechaVenta { get; set; }
        public int ClienteId { get; set; }
        public int UsuarioId { get; set; }
        public int TipoSalidaId { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFacVenta> DetalleFacVenta { get; set; }
        public virtual TipoSalida TipoSalida { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
