//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSistema.ModeloDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permiso
    {
        public int Id { get; set; }
        public int IdRol { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> Fehacreacion { get; set; }
    
        public virtual Rol Rol { get; set; }
    }
}
