//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSistema.ModeloDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.FacturaCompra = new HashSet<FacturaCompra>();
            this.FacturaVenta = new HashSet<FacturaVenta>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string NombreCompleto { get; set; }
        public string Clave { get; set; }
        public string Correo { get; set; }
        public int IdRol { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> Fechacreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaCompra> FacturaCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaVenta> FacturaVenta { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
